# Generated by Django 6.0.5 on 2026-06-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_settings_userprofile_weekend_day_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='backdated_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='timelog',
            name='is_backdated',
            field=models.BooleanField(default=False),
        ),
    ]
